// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// LoadOKCode is the HTTP code returned for type LoadOK
const LoadOKCode int = 200

/*LoadOK OK

swagger:response loadOK
*/
type LoadOK struct {

	/*
	  In: Body
	*/
	Payload *LoadOKBody `json:"body,omitempty"`
}

// NewLoadOK creates LoadOK with default headers values
func NewLoadOK() *LoadOK {

	return &LoadOK{}
}

// WithPayload adds the payload to the load o k response
func (o *LoadOK) WithPayload(payload *LoadOKBody) *LoadOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the load o k response
func (o *LoadOK) SetPayload(payload *LoadOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *LoadOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
