// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// LoadDataOKCode is the HTTP code returned for type LoadDataOK
const LoadDataOKCode int = 200

/*LoadDataOK OK

swagger:response loadDataOK
*/
type LoadDataOK struct {

	/*
	  In: Body
	*/
	Payload *LoadDataOKBody `json:"body,omitempty"`
}

// NewLoadDataOK creates LoadDataOK with default headers values
func NewLoadDataOK() *LoadDataOK {

	return &LoadDataOK{}
}

// WithPayload adds the payload to the load data o k response
func (o *LoadDataOK) WithPayload(payload *LoadDataOKBody) *LoadDataOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the load data o k response
func (o *LoadDataOK) SetPayload(payload *LoadDataOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *LoadDataOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
