// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// LoadDataHandlerFunc turns a function with the right signature into a load data handler
type LoadDataHandlerFunc func(LoadDataParams) middleware.Responder

// Handle executing the request and returning a response
func (fn LoadDataHandlerFunc) Handle(params LoadDataParams) middleware.Responder {
	return fn(params)
}

// LoadDataHandler interface for that can handle valid load data params
type LoadDataHandler interface {
	Handle(LoadDataParams) middleware.Responder
}

// NewLoadData creates a new http.Handler for the load data operation
func NewLoadData(ctx *middleware.Context, handler LoadDataHandler) *LoadData {
	return &LoadData{Context: ctx, Handler: handler}
}

/* LoadData swagger:route GET /load_data loadData

load json file

*/
type LoadData struct {
	Context *middleware.Context
	Handler LoadDataHandler
}

func (o *LoadData) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewLoadDataParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// LoadDataOKBody load data o k body
//
// swagger:model LoadDataOKBody
type LoadDataOKBody struct {

	// status
	Status string `json:"status,omitempty"`
}

// Validate validates this load data o k body
func (o *LoadDataOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this load data o k body based on context it is used
func (o *LoadDataOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *LoadDataOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *LoadDataOKBody) UnmarshalBinary(b []byte) error {
	var res LoadDataOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
