// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// LoadHandlerFunc turns a function with the right signature into a load handler
type LoadHandlerFunc func(LoadParams) middleware.Responder

// Handle executing the request and returning a response
func (fn LoadHandlerFunc) Handle(params LoadParams) middleware.Responder {
	return fn(params)
}

// LoadHandler interface for that can handle valid load params
type LoadHandler interface {
	Handle(LoadParams) middleware.Responder
}

// NewLoad creates a new http.Handler for the load operation
func NewLoad(ctx *middleware.Context, handler LoadHandler) *Load {
	return &Load{Context: ctx, Handler: handler}
}

/* Load swagger:route GET /load_data load

load json file

*/
type Load struct {
	Context *middleware.Context
	Handler LoadHandler
}

func (o *Load) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewLoadParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// LoadOKBody load o k body
//
// swagger:model LoadOKBody
type LoadOKBody struct {

	// status
	Status string `json:"status,omitempty"`
}

// Validate validates this load o k body
func (o *LoadOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this load o k body based on context it is used
func (o *LoadOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *LoadOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *LoadOKBody) UnmarshalBinary(b []byte) error {
	var res LoadOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
