// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// SearchHandlerFunc turns a function with the right signature into a search handler
type SearchHandlerFunc func(SearchParams) middleware.Responder

// Handle executing the request and returning a response
func (fn SearchHandlerFunc) Handle(params SearchParams) middleware.Responder {
	return fn(params)
}

// SearchHandler interface for that can handle valid search params
type SearchHandler interface {
	Handle(SearchParams) middleware.Responder
}

// NewSearch creates a new http.Handler for the search operation
func NewSearch(ctx *middleware.Context, handler SearchHandler) *Search {
	return &Search{Context: ctx, Handler: handler}
}

/* Search swagger:route GET /search search

elasticsearch search api

*/
type Search struct {
	Context *middleware.Context
	Handler SearchHandler
}

func (o *Search) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewSearchParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
