// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "description": "NFL Player Stats",
    "title": "nfl-rushing",
    "version": "0.1.0"
  },
  "paths": {
    "/load_data": {
      "get": {
        "description": "load json file",
        "produces": [
          "application/json"
        ],
        "operationId": "load_data",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/ping": {
      "get": {
        "description": "Ping route for health checks.",
        "produces": [
          "text/plain; charset=utf-8"
        ],
        "operationId": "ping",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/search": {
      "get": {
        "description": "elasticsearch search api",
        "produces": [
          "application/json"
        ],
        "operationId": "search",
        "parameters": [
          {
            "type": "string",
            "description": "player name to search for",
            "name": "player_name",
            "in": "query"
          },
          {
            "type": "string",
            "description": "Total Rushing Touchdowns, Longest Rush and Total Rushing Yards",
            "name": "sort",
            "in": "query"
          },
          {
            "type": "string",
            "description": "Total Rushing Touchdowns",
            "name": "td",
            "in": "query"
          },
          {
            "type": "string",
            "description": "Longest Rush -- a T represents a touchdown occurred",
            "name": "lng",
            "in": "query"
          },
          {
            "type": "string",
            "description": "Total Rushing Yards",
            "name": "yds",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/SearchResponseBody"
            }
          },
          "500": {
            "description": "Server Error",
            "schema": {
              "$ref": "#/definitions/BadRequestResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "BadRequestResponse": {
      "type": "object",
      "properties": {
        "error": {
          "description": "Optional error message for non-fatal errors.",
          "type": "string"
        }
      }
    },
    "NFLPlayer": {
      "type": "object",
      "properties": {
        "att": {
          "type": "number",
          "x-nullable": false,
          "x-omitempty": false
        },
        "att_per_game": {
          "type": "number",
          "x-nullable": false,
          "x-omitempty": false
        },
        "avg": {
          "type": "number",
          "x-nullable": false,
          "x-omitempty": false
        },
        "first": {
          "type": "number",
          "x-nullable": false,
          "x-omitempty": false
        },
        "first_percentage": {
          "type": "number",
          "x-nullable": false,
          "x-omitempty": false
        },
        "fourty_plus": {
          "type": "number",
          "x-nullable": false,
          "x-omitempty": false
        },
        "fum": {
          "type": "number",
          "x-nullable": false,
          "x-omitempty": false
        },
        "lng": {
          "type": "string",
          "x-nullable": false,
          "x-omitempty": false
        },
        "player": {
          "type": "string",
          "x-nullable": false,
          "x-omitempty": false
        },
        "pos": {
          "type": "string",
          "x-nullable": false,
          "x-omitempty": false
        },
        "td": {
          "type": "number",
          "x-nullable": false,
          "x-omitempty": false
        },
        "team": {
          "type": "string",
          "x-nullable": false,
          "x-omitempty": false
        },
        "twenty_plus": {
          "type": "number",
          "x-nullable": false,
          "x-omitempty": false
        },
        "yds_per_game": {
          "type": "number",
          "x-nullable": false,
          "x-omitempty": false
        },
        "ydsclean": {
          "type": "number",
          "x-nullable": false,
          "x-omitempty": false
        }
      }
    },
    "SearchResponseBody": {
      "type": "object",
      "properties": {
        "nfl_players": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/NFLPlayer"
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "description": "NFL Player Stats",
    "title": "nfl-rushing",
    "version": "0.1.0"
  },
  "paths": {
    "/load_data": {
      "get": {
        "description": "load json file",
        "produces": [
          "application/json"
        ],
        "operationId": "load_data",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/ping": {
      "get": {
        "description": "Ping route for health checks.",
        "produces": [
          "text/plain; charset=utf-8"
        ],
        "operationId": "ping",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/search": {
      "get": {
        "description": "elasticsearch search api",
        "produces": [
          "application/json"
        ],
        "operationId": "search",
        "parameters": [
          {
            "type": "string",
            "description": "player name to search for",
            "name": "player_name",
            "in": "query"
          },
          {
            "type": "string",
            "description": "Total Rushing Touchdowns, Longest Rush and Total Rushing Yards",
            "name": "sort",
            "in": "query"
          },
          {
            "type": "string",
            "description": "Total Rushing Touchdowns",
            "name": "td",
            "in": "query"
          },
          {
            "type": "string",
            "description": "Longest Rush -- a T represents a touchdown occurred",
            "name": "lng",
            "in": "query"
          },
          {
            "type": "string",
            "description": "Total Rushing Yards",
            "name": "yds",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/SearchResponseBody"
            }
          },
          "500": {
            "description": "Server Error",
            "schema": {
              "$ref": "#/definitions/BadRequestResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "BadRequestResponse": {
      "type": "object",
      "properties": {
        "error": {
          "description": "Optional error message for non-fatal errors.",
          "type": "string"
        }
      }
    },
    "NFLPlayer": {
      "type": "object",
      "properties": {
        "att": {
          "type": "number",
          "x-nullable": false,
          "x-omitempty": false
        },
        "att_per_game": {
          "type": "number",
          "x-nullable": false,
          "x-omitempty": false
        },
        "avg": {
          "type": "number",
          "x-nullable": false,
          "x-omitempty": false
        },
        "first": {
          "type": "number",
          "x-nullable": false,
          "x-omitempty": false
        },
        "first_percentage": {
          "type": "number",
          "x-nullable": false,
          "x-omitempty": false
        },
        "fourty_plus": {
          "type": "number",
          "x-nullable": false,
          "x-omitempty": false
        },
        "fum": {
          "type": "number",
          "x-nullable": false,
          "x-omitempty": false
        },
        "lng": {
          "type": "string",
          "x-nullable": false,
          "x-omitempty": false
        },
        "player": {
          "type": "string",
          "x-nullable": false,
          "x-omitempty": false
        },
        "pos": {
          "type": "string",
          "x-nullable": false,
          "x-omitempty": false
        },
        "td": {
          "type": "number",
          "x-nullable": false,
          "x-omitempty": false
        },
        "team": {
          "type": "string",
          "x-nullable": false,
          "x-omitempty": false
        },
        "twenty_plus": {
          "type": "number",
          "x-nullable": false,
          "x-omitempty": false
        },
        "yds_per_game": {
          "type": "number",
          "x-nullable": false,
          "x-omitempty": false
        },
        "ydsclean": {
          "type": "number",
          "x-nullable": false,
          "x-omitempty": false
        }
      }
    },
    "SearchResponseBody": {
      "type": "object",
      "properties": {
        "nfl_players": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/NFLPlayer"
          }
        }
      }
    }
  }
}`))
}
