// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NFLPlayer n f l player
//
// swagger:model NFLPlayer
type NFLPlayer struct {

	// att
	Att float64 `json:"att"`

	// att per game
	AttPerGame float64 `json:"att_per_game"`

	// avg
	Avg float64 `json:"avg"`

	// first
	First float64 `json:"first"`

	// first percentage
	FirstPercentage float64 `json:"first_percentage"`

	// fourty plus
	FourtyPlus float64 `json:"fourty_plus"`

	// fum
	Fum float64 `json:"fum"`

	// lng
	Lng string `json:"lng"`

	// player
	Player string `json:"player"`

	// pos
	Pos string `json:"pos"`

	// td
	Td float64 `json:"td"`

	// team
	Team string `json:"team"`

	// twenty plus
	TwentyPlus float64 `json:"twenty_plus"`

	// yds per game
	YdsPerGame float64 `json:"yds_per_game"`

	// ydsclean
	Ydsclean float64 `json:"ydsclean"`
}

// Validate validates this n f l player
func (m *NFLPlayer) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this n f l player based on context it is used
func (m *NFLPlayer) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NFLPlayer) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NFLPlayer) UnmarshalBinary(b []byte) error {
	var res NFLPlayer
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
