// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NFLPlayers n f l players
//
// swagger:model NFLPlayers
type NFLPlayers struct {

	// att
	Att string `json:"att"`

	// att per game
	AttPerGame string `json:"att_per_game"`

	// avg
	Avg string `json:"avg"`

	// first
	First string `json:"first"`

	// first percentage
	FirstPercentage string `json:"first_percentage"`

	// fourty plus
	FourtyPlus string `json:"fourty_plus"`

	// fum
	Fum string `json:"fum"`

	// lng
	Lng string `json:"lng"`

	// player
	Player string `json:"player"`

	// pos
	Pos string `json:"pos"`

	// td
	Td string `json:"td"`

	// team
	Team string `json:"team"`

	// twenty plus
	TwentyPlus string `json:"twenty_plus"`

	// yds
	Yds string `json:"yds"`

	// yds per game
	YdsPerGame string `json:"yds_per_game"`
}

// Validate validates this n f l players
func (m *NFLPlayers) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this n f l players based on context it is used
func (m *NFLPlayers) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NFLPlayers) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NFLPlayers) UnmarshalBinary(b []byte) error {
	var res NFLPlayers
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
