// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SearchResponseBody search response body
//
// swagger:model SearchResponseBody
type SearchResponseBody struct {

	// nfl players
	NflPlayers []*NFLPlayer `json:"nfl_players"`
}

// Validate validates this search response body
func (m *SearchResponseBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNflPlayers(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SearchResponseBody) validateNflPlayers(formats strfmt.Registry) error {
	if swag.IsZero(m.NflPlayers) { // not required
		return nil
	}

	for i := 0; i < len(m.NflPlayers); i++ {
		if swag.IsZero(m.NflPlayers[i]) { // not required
			continue
		}

		if m.NflPlayers[i] != nil {
			if err := m.NflPlayers[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("nfl_players" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("nfl_players" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this search response body based on the context it is used
func (m *SearchResponseBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateNflPlayers(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SearchResponseBody) contextValidateNflPlayers(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.NflPlayers); i++ {

		if m.NflPlayers[i] != nil {
			if err := m.NflPlayers[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("nfl_players" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("nfl_players" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *SearchResponseBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SearchResponseBody) UnmarshalBinary(b []byte) error {
	var res SearchResponseBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
